name: "Dreamer's Refuge"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130900'
    - '#644d24'
    - '#718059'
    - '#93a29e'
    - '#cfc39d'
  brandStrength: 0.42566091124899685
  lightness: 0.1550034291576594
  saturation: 0.4113883743993938
  rhythmicContrast: 0.13428710750304163
purpose: []
